language: python
python:
    - "3.6"
# command to install dependencies
install:
    - pip install .
    - pip install pep8
    - pip install coverage
    - pip install coveralls
before_script:
    - cp travis_ci/manage.py manage.py
    - python manage.py syncdb --noinput
# command to run tests
script:
    - pep8 spacescout_labstats/
    - coverage run --source=spacescout_labstats/ manage.py test spacescout_labstats 
after_script:
    - coveralls
