from spacescout_labstats.test.test_online_labstats import OnlineLabstatsTest
from spacescout_labstats.test.test_utils import UtilsTest
from spacescout_labstats.test.test_cte_techloan import CTETechloanTest
from spacescout_labstats.test.upload import UploadTest
