from spacescout_labstats.test.test_seattle_labstats import SeattleLabstatsTest
from spacescout_labstats.test.test_online_labstats import OnlineLabstatsTest
from spacescout_labstats.test.test_utils import UtilsTest
from spacescout_labstats.test.test_k2 import K2Test
from spacescout_labstats.test.upload import UploadTest
