from spacescout_labstats.test.test_seattle_labstats import SeattleLabstatsTest
from spacescout_labstats.test.test_online_labstats import OnlineLabstatsTest
from spacescout_labstats.test.test_utils import UtilsTest
